### ISSUE TITLE
Problema crítico a la hora de hacer merge

### ISSUE THREAD

**Issue by alechamed** [alechamed/decideEuropa-censo#3]
Temática: Code
Prioridad: Critical

Los commits han sido los siguientes: 
ae8bc50cc6ba57c007474647f0c9846763f6ff83
1da4dbd88d30a804a7dd880bf2f84dd5f527b8db
6abe2b5197f3cc91e5295cdcac54eced01c2401b

Se han borrado un monton de ficheros y no se puede ejecutar el proyecto. Se comentó que los merge se hacían en Dev. Antes de hacer un merge, comprobar que en local funcionara todo.

**Comment by Escrabel** [comment]
La solucion que hemos pensado @ordomedina @jullopjim1 y yo es hacer un revert al commit del merge,

**Comment by alechamed** [comment]
He comprobado que todo funciona de nuevo correctamente.
