### ISSUE TITLE
Investigar importacion de ldap para implementar

### ISSUE THREAD

**Issue by alechamed** [alechamed/decideEuropa-censo#35]
Yo @alechamed quiero investigar sobre como se podría importar desde ldap, ire poniendo propuestas como comentarios y cuando se llegue a una solucion se cerrará y se procederá a ejecutar las propuestas.

**Comment by alechamed** [comment]
Según he visto en internet, una query de usuarios de ldap puede devolver esta estructura:
```
dn: uid=jsmith1,ou=People,dc=example,dc=com

dn: uid=sbrown20,ou=People,dc=example,dc=com

```

Por lo tanto, creo que se podría hacer un botón para cargar un fichero, leerlo y buscar los diferentes uid, si coinciden con los usernames de nuestra base de datos se puede aprovechar la vista que hizo @Escrabel de reutilización de censo en otra votación.

Esta decisión si la mayoría la ve bien, se cerrará la issue de investigación y se procederá a la implementación.

@alechamed 
@Jesusmtorres97 
@Escrabel 
@ordomedina 
@jullopjim1

**Comment by jullopjim1** [comment]
Yo lo veo bien, podriamos intentar eso que comentas @alechamed

**Comment by Escrabel** [comment]
Lo veo bien

**Comment by AntonioVP** [comment]
A mi me parece bien, se puede intentar.

**Comment by alechamed** [comment]
Vale, voy a cerrar la issue de investigación para que se abra una de realización.
