### ISSUE TITLE
Realizar test de la funcionalidad de importación.

### ISSUE THREAD

**Issue by ordomedina** [alechamed/decideEuropa-censo#7]
@ordomedina cambia el estado a ACCEPTED, le doy el visto bueno.

**Comment by ordomedina** [comment]
No consigo hacer el test. Se lo asigno a @Escrabel para que intente hacerlo.

**Comment by Escrabel** [comment]
Yo tampoco sé cómo hacerlo en el poco tiempo que queda hasta la entrega
